identifier = "oneOrAll_test"
events = 3000000
repetitions = 20
cores = 32

arrival.distribution = "exponential"

service.distribution = "exponential"


[[class]]
cores = 1
arrival.prob = 0.9
service.mean = 1

[[class]]
cores = 32
arrival.prob = 0.1
service.mean = 1


[[pivot]]
policy = [
    "fifo",
#    "back filling",
#    "most server first",
#    "server filling memoryful",
#    { name ="quick swap", threshold = 1 },
#    { name ="quick swap", threshold = 32 },
#    "first fit",
#    "adaptive msf",
#    "static msf",
#    { name = "smash", window = 2 },
#    { name = "smash", window = 5 },
#    { name = "smash", window = 10 },
]
arrival.rate = [
    2.7
#    6.25,
#    6.5,
#    6.75,
#    7,
]
arrival.autocorr = [
    1,10
]
